AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an ECS Cluster

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'OPAHookBugBashCluster-${AWS::StackName}'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Environment
          Value: Production