AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an ECS Cluster

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: OPAHookBugBashClusterShouldFail
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      Tags:
        - Key: Environment
          Value: Production